.docker:image:build:
  stage: build
  services:
    - docker:dind
  image: bborysenko/swarm-deploy-helper
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - source $CI_SCRIPTS_LIBS/docker.sh
  script:
    - docker:registry:login
    - docker:image:build
  only:
    refs:
      - branches
